TOP=../..
.include "$(TOP)/mk/os161.config.mk"

SUBDIRS=\
	simplewrite \
	simpleopen \
	lseekargs \
	simpleerr \
	dup2 \
	cwd \
	getpid \
	onefork \
	twofork \
	args \
	execv

.include "$(TOP)/mk/os161.subdir.mk"
